#pragma config(Sensor, S1,     LightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          RightMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int BlackFloor;

// Return the value of the sensor plugged into S1 Port
int getSensorValue (){
	return SensorValue[LightSensor];
}

// Determine if the sensor sees the white line
bool isWhiteLine() {
	return (getSensorValue() > BlackFloor);
}

// back the robot up for mSecs
void backup( int mSec) {
	motor[LeftMotor] = -50;
	motor[RightMotor] = -50;
	wait1Msec(mSec);
}

// find a random number and have the robot turn for that amount of time
void randomTurn() {
	int maxTime = 1000;
	int minTime = 250;
	int ms = (rand() % (maxTime - minTime)) + minTime;
	motor[LeftMotor] = 100;
	motor[RightMotor] = -100;
	wait1Msec (ms);
}


// Main task and loop starts here
task main()
{
	srand(nSysTime);  // generate seed for rand() from current system time
	BlackFloor = SensorValue[S1] + 5; //self calibrate the light sensor
	wait1Msec(5000);  // Mandatory wait 5 seconds before starting

	while(true) 	{
		wait1Msec(0);    // Let the nxt do some other stuff to release the proc
		motor[LeftMotor] = 100;   // Left motor 100 %
		motor[RightMotor] = 100;  // Right otor 100 %

		if (isWhiteLine())	{ // Do we see the line
			backup(500);   // backup for 500 mSecs
			randomTurn();  // execute a random turn
		}
	}
}
