
#pragma config(Sensor, S1,     RightLight,     sensorLightActive)
#pragma config(Sensor, S2,     FrontLight,     sensorLightActive)
#pragma config(Sensor, S3,     LeftLight,      sensorLightActive)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          RightMotor,    tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          CenterMotor,   tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int lowPower=5;
	int highPower=95;
	int midPower = (int) (highPower + lowPower)/3;
	motor[CenterMotor] = midPower;
	while (true) {
		if (SensorValue [FrontLight] > 50) {
			motor[LeftMotor] = lowPower;
			motor[RightMotor] = highPower;
		}
		else {
			motor[LeftMotor]=highPower;
			motor[RightMotor]=lowPower;
		}
		Sleep(0);
	}
	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
}
